# Generated by Django 5.1.7 on 2025-07-20 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.TextField(max_length=255)),
                ('customerId', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
