# Generated by Django 5.1.7 on 2025-07-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginTable',
        ),
    ]
