# Generated by Django 5.1.7 on 2025-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_login_logintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='password',
            field=models.CharField(default=9999999999, max_length=255),
            preserve_default=False,
        ),
    ]
