# Generated by Django 5.1.7 on 2025-07-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_customer_cart_customerid'),
        ('login', '0003_logintable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='login.logintable', to_field='customerId'),
        ),
    ]
