# Generated by Django 5.1.7 on 2025-07-20 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ItemId', models.CharField(default=uuid.uuid4, editable=False, max_length=12, unique=True)),
            ],
        ),
    ]
