# Generated by Django 5.1.7 on 2025-07-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsBuy',
            new_name='Shop',
        ),
    ]
