# Generated by Django 5.1.7 on 2025-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_itemsbuy_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
